Feature/chromecast events
meisterplayer/meisterplayer pull request #86
Opened 2018-03-21 09:02 UTC by buttonfreak

2018-03-21 09:06 UTC, buttonfreak commented
Use https://github.com/meisterplayer/meister-cast-target-template as target

2018-03-21 15:58 UTC, FranklinWaller commented
Can't this be placed in the chromecast plugin? Because Meistercore doesn't really have anything to do with chromecast

2018-03-22 06:41 UTC, buttonfreak commented
I thought these events should be defined here, like other plugins (like ads). In the end all events available are defined in one place (core)

2018-03-26 07:01 UTC, Thomasvdam requested changes
I also agree with Franklin's comment that ideally plugin specific events shouldn't be declared in the core. We declared the ad events here with the idea that they could be universal among different ad providers.

Now that I'm thinking about it this entire section is rather pointless, as the only real function it has is to prevent a console.warn from displaying when firing an event that has no listeners. And I suppose it also serves as a lackluster reference of possible event names, but without any way to import/use the exact strings in other plugins it makes very little sense. This is something we should take a closer look at when cleaning up the event bus.

2018-03-26 07:01 UTC, Thomasvdam commented on src/js/events/chromecastreceiver-events.js
> +    'canPlay',
Shouldn't there be something in the event name to indicate this is exclusive to ChromeCast? I see several names that are ambiguous and could easily apply to several other plugins.

2018-03-26 07:03 UTC, Thomasvdam commented
To clarify: I don't see placing these events here as a problem for this pull request, that's a new issue all by itself. But I do think that these events should be namespaced in some way to at least make them a little bit more meaningful. :)

2018-03-26 12:32 UTC, buttonfreak commented
In meister6 we should rethink how events are exposed.. For now I renamed events to their own namespace

2018-03-26 12:34 UTC, Thomasvdam approved these changes

2018-03-26 12:35 UTC, merged